-- ============================================================
-- SMP THHK Sumatif Exam Portal — Supabase Schema (Kondisi Akhir)
--
-- Untuk database yang sudah berjalan, jalankan BERURUTAN di
-- Supabase Dashboard → SQL Editor:
--   1. migrations/000_emergency_lockdown.sql   (Fase 0)
--   2. migrations/001_server_authority.sql     (Fase 1)
--
-- Setelah Fase 1, TIDAK ada policy anon pada tabel apa pun kecuali
-- violation_logs (insert-only). Semua akses lewat RPC security definer
-- yang menerima PIN sebagai argumen (tanpa JWT).
-- ============================================================

-- Prasyarat tabel dibuat melalui migrations/001_server_authority.sql.
-- File ini adalah referensi skema akhir untuk dokumentasi & setup baru.

-- Ringkasan tabel (dibuat oleh 001_server_authority.sql):
--   exams               — bank soal (rename dari exam_sessions), kolom is_active
--   exam_tokens         — token aktif per ruang (rotasi 15 menit, server)
--   room_pins           — PIN per ruang + super_admin, ter-hash bcrypt
--   attendance          — presensi + TTD siswa (unique nisn+exam_id)
--   student_sessions    — sesi live siswa (heartbeat)
--   official_minutes    — berita acara per ruang (jsonb)
--   app_settings        — saklar master (token_access_enabled)
--   students            — roster siswa (dari Fase 0, tetap)
--   violation_logs      — log pelanggaran (insert-only anon, tanpa baca)

-- RPC yang tersedia (semua security definer, grant execute ke anon):
--   Jalur siswa:   check_token, open_exam, heartbeat
--   Jalur panel:   verify_pin, release_token, current_token,
--                  proctor_dashboard, save_minutes
--   Admin:         admin_list_exams, admin_upsert_exam, admin_delete_exam,
--                  admin_set_active_exams, admin_list_students,
--                  admin_add_student, admin_bulk_add_students,
--                  admin_delete_student, toggle_token_access,
--                  get_token_access, set_room_pin
